name: her
channels:
    - https://conda.anaconda.org/kne
    - https://conda.anaconda.org/tlatorre
    - https://conda.anaconda.org/cjs14
    - https://conda.anaconda.org/menpo
    - jjhelmus
    - soumith
dependencies:
    - python==3.5.4
    - numpy==1.11.2
    - scipy
    - flask
    - path.py
    - matplotlib
    - scikit-learn
    - pytorch
    - torchvision
    - mpi4py==3.0.0
    - plotly
    - joblib
    - pip:
        - Pillow
        - atari-py
        - pyprind
        - ipdb
        - boto3
        - PyOpenGL
        - mujoco-py<1.50.2,>=1.50.1
        - cached_property
        - line_profiler
        - cloudpickle
        - Cython
        - git+https://github.com/plotly/plotly.py.git@2594076e29584ede2d09f2aa40a8a195b3f3fc66#egg=plotly
        - awscli
        - gym
        - pyglet
        - git+https://github.com/neocxi/prettytensor.git
        - jupyter
        - progressbar2
        - chainer==1.18.0
        - tensorflow-gpu==1.5.0
        - tensorflow==1.5.0
        - dominate
        - scikit-image
